In [2]:
import pandas as pd

In [3]:
dict_data = {
    "c1": ["a", "b", "c", "d", "e"],
    "c2": [1, 1, 1, 2, 2],
    "c3": [1, 1, 2, 2, 2]
}

df = pd.DataFrame(dict_data)
df

  c1  c2  c3
0  a   1   1
1  b   1   1
2  c   1   2
3  d   2   2
4  e   2   2

In [4]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [5]:
df.duplicated(keep = "last")

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [6]:
df.duplicated(keep=False)

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [8]:
df["c2"].duplicated()

0    False
1     True
2     True
3    False
4     True
Name: c2, dtype: bool

In [9]:
df.duplicated(subset=["c2"])

0    False
1     True
2     True
3    False
4     True
dtype: bool

In [ ]:
# 중복 데이터 제거

df

  c1  c2  c3
0  a   1   1
1  b   1   1
2  c   1   2
3  d   2   2
4  e   2   2

In [ ]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [ ]:
df2 = df.drop_duplicates()
df2

  c1  c2  c3
0  a   1   1
1  b   1   1
2  c   1   2
3  d   2   2
4  e   2   2

In [11]:
df3= df.drop_duplicates(keep="last")
df3

  c1  c2  c3
0  a   1   1
1  b   1   1
2  c   1   2
3  d   2   2
4  e   2   2

In [12]:
df4 = df.drop_duplicates(keep=False)
df4

  c1  c2  c3
0  a   1   1
1  b   1   1
2  c   1   2
3  d   2   2
4  e   2   2

In [13]:
df

  c1  c2  c3
0  a   1   1
1  b   1   1
2  c   1   2
3  d   2   2
4  e   2   2

In [14]:
df5= df.drop_duplicates(subset=["c2", "c3"])
df5

  c1  c2  c3
0  a   1   1
2  c   1   2
3  d   2   2

In [15]:
df.drop_duplicates(subset=["c2", "c3"], keep=False)

  c1  c2  c3
2  c   1   2