In [2]:
import pandas as pd

data = {'name' : [ 'Jerry', 'Riah', 'Paul'],
        'algol' : [ "A", "A+", "B"],
        'basic' : [ "C", "B", "B+"],
        'c++' : [ "B+", "C", "C+"],
        }

df = pd.DataFrame(data)
df.set_index("name", inplace= True)

df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [3]:
df.to_csv("./data/df_sample.csv")

In [4]:
df.to_csv("./data/df_sample.csv", index = False)

In [5]:
# json파일로 저장

import pandas as pd

df

      algol basic c++
name
Jerry     A     C  B+
Riah     A+     B   C
Paul      B    B+  C+

In [6]:
df.to_json("./data/df_sample.json")

In [8]:
# 엑셀 파일로 저장
df.to_excel("./data/df_sample.xlsx")

In [9]:
df.to_excel("./data/df_sample2.xlsx", index = False)